Repository GentenStudios/Phoenix, pull requests merged in 2020-01, with the labels that each got.

#7 Settings
  Engine/CMakeLists.txt
  Engine/Include/Quartz2/Camera.hpp
  Engine/Include/Quartz2/Settings.hpp
  Engine/Source/Camera.cpp
  Engine/Source/Settings.cpp
Labels: enhancement

#31 Setup Linux + MacOSX CI Support w/ TravisCI.
  .gitignore
  .travis.yml
  CMakeLists.txt
  Engine/CMakeLists.txt
  Engine/ThirdParty/ImGui/CMakeLists.txt
Labels: ci, enhancement, platform-linux, platform-macos, priority-high

#52 Update licenses to 2019-20.
  Engine/Include/Quartz2/BlocksRegistry.hpp
  Engine/Include/Quartz2/BlocksTextureAtlas.hpp
  Engine/Include/Quartz2/Camera.hpp
  Engine/Include/Quartz2/Chunk.hpp
  Engine/Include/Quartz2/ChunkRenderer.hpp
  Engine/Include/Quartz2/Game.hpp
  Engine/Include/Quartz2/Math.hpp
  Engine/Include/Quartz2/MathUtils.hpp
  Engine/Include/Quartz2/Matrix4x4.hpp
  Engine/Include/Quartz2/Mesh.hpp
  Engine/Include/Quartz2/OpenGL32.hpp
  Engine/Include/Quartz2/Quartz.hpp
  Engine/Include/Quartz2/Ray.hpp
  Engine/Include/Quartz2/Rect.hpp
  Engine/Include/Quartz2/Settings.hpp
  Engine/Include/Quartz2/ShaderCompiler.hpp
  Engine/Include/Quartz2/Singleton.hpp
  Engine/Include/Quartz2/Vec2.hpp
  Engine/Include/Quartz2/Vec3.hpp
  Engine/Include/Quartz2/Vertex.hpp
  Engine/Include/Quartz2/VoxelWorld.hpp
  Engine/Source/BlocksRegistry.cpp
  Engine/Source/BlocksTextureAtlas.cpp
  Engine/Source/Camera.cpp
  Engine/Source/Chunk.cpp
  Engine/Source/ChunkRenderer.cpp
  Engine/Source/Game.cpp
  Engine/Source/Matrix4x4.cpp
  Engine/Source/Mesh.cpp
  Engine/Source/OpenGL32.cpp
  Engine/Source/Ray.cpp
  Engine/Source/Settings.cpp
  Engine/Source/ShaderCompiler.cpp
  Engine/Source/VoxelWorld.cpp
Labels: documentation

#48 Feat doxy
  .gitignore
  Doxyfile
Labels: documentation, priority-medium

#54 Move lua/liblua into Dependencies source group (mainly for VS.)
  Engine/ThirdParty/CMakeLists.txt
Labels: enhancement, platform-windows

#56 Event System
  Engine/Include/Quartz2/CMakeLists.txt
  Engine/Include/Quartz2/EnumTools.hpp
  Engine/Include/Quartz2/Events/CMakeLists.txt
  Engine/Include/Quartz2/Events/Event.hpp
  Engine/Include/Quartz2/Events/IEventListener.hpp
  Engine/Include/Quartz2/Events/Keys.hpp
  Engine/Source/CMakeLists.txt
  Sandbox/Source/Main.cpp
Labels: enhancement, graphics, priority-high

#57 Namespaced + Enhanced Maths System
  Engine/Include/Quartz2/BlocksTextureAtlas.hpp
  Engine/Include/Quartz2/CMakeLists.txt
  Engine/Include/Quartz2/Camera.hpp
  Engine/Include/Quartz2/Math/CMakeLists.txt
  Engine/Include/Quartz2/Math/Math.hpp
  Engine/Include/Quartz2/Math/MathUtils.hpp
  Engine/Include/Quartz2/Math/Matrix4x4.hpp
  Engine/Include/Quartz2/Math/Ray.hpp
  Engine/Include/Quartz2/Math/Rect.hpp
  Engine/Include/Quartz2/Math/Vector2.hpp
  Engine/Include/Quartz2/Math/Vector3.hpp
  Engine/Include/Quartz2/Quartz.hpp
  Engine/Include/Quartz2/Vec2.hpp
  Engine/Include/Quartz2/Vec3.hpp
  Engine/Include/Quartz2/Vertex.hpp
  Engine/Source/CMakeLists.txt
  Engine/Source/Camera.cpp
  Engine/Source/Chunk.cpp
  Engine/Source/ChunkRenderer.cpp
  Engine/Source/Math/CMakeLists.txt
  Engine/Source/Math/Matrix4x4.cpp
  Engine/Source/Math/Ray.cpp
Labels: enhancement, priority-high

#64 Block + Texture Registry
  Engine/Include/Quartz2/CMakeLists.txt
  Engine/Include/Quartz2/Voxels/Block.hpp
  Engine/Include/Quartz2/Voxels/BlockRegistry.hpp
  Engine/Include/Quartz2/Voxels/CMakeLists.txt
  Engine/Include/Quartz2/Voxels/TextureRegistry.hpp
  Engine/Source/CMakeLists.txt
  Engine/Source/Voxels/BlockRegistry.cpp
  Engine/Source/Voxels/CMakeLists.txt
  Engine/Source/Voxels/TextureRegistry.cpp
Labels: enhancement, priority-high, voxels

#66 Add Travis CI build badge.
  README.md
Labels: ci, documentation
